Scalars in PyTorch

In [198]:
import torch

In [199]:
x_pt = torch.tensor(10)
x_pt

tensor(10)

In [200]:
x_pt.shape #Scalar tensor has no dimention. Only magnitude.

torch.Size([])

Scalars in TensorFlow

In [201]:
import tensorflow as tf

In [202]:
x_tf = tf.Variable(10, dtype=tf.int16)

In [203]:
x_tf

<tf.Variable 'Variable:0' shape=() dtype=int16, numpy=10>

In [204]:
x_tf.shape

TensorShape([])

In [205]:
y_tf = tf.Variable(15, dtype=tf.int16)

In [206]:
x_tf + y_tf #Overloading the operators. Using base Python operators on tensors.

<tf.Tensor: shape=(), dtype=int16, numpy=25>

In [207]:
tf_sum = tf.add(x_tf, y_tf)
tf_sum

<tf.Tensor: shape=(), dtype=int16, numpy=25>

In [208]:
tf_sum.numpy()

np.int16(25)

Vectors in NumPy  
#arrays cannot be created in base Python

In [209]:
import numpy as np

In [210]:
x = np.array([10, 20, 30])
x

array([10, 20, 30])

In [211]:
len(x)

3

In [212]:
x.shape

(3,)

In [213]:
type(x)

numpy.ndarray

In [214]:
x[0]

np.int64(10)

Vector Transposition

Transposing a regular 1-D array has not effect, unless we use a nested "matrix-style" bracket.

In [215]:
x

array([10, 20, 30])

In [216]:
x_t = x.T
x_t

array([10, 20, 30])

In [217]:
y = np.array([[10, 20, 30]])
y

array([[10, 20, 30]])

In [218]:
y.T

array([[10],
       [20],
       [30]])

Zero vectors

In [219]:
z = np.zeros(3)
z

array([0., 0., 0.])

Vectors in PyTorch and TensorFlow

In [220]:
x_pt = torch.tensor([1, 2, 3])
x_pt

tensor([1, 2, 3])

In [221]:
x_tf = tf.Variable([1, 2, 3])
x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

L<sup>2</sup> Norm

In [222]:
x

array([10, 20, 30])

In [223]:
np.linalg.norm(x)

np.float64(37.416573867739416)

L<sup>1</sup> Norm

In [224]:
np.linalg.norm(x, ord= 1)

np.float64(60.0)

Squared L<sup>2</sup> Norm

In [225]:
x

array([10, 20, 30])

In [226]:
np.dot(x, x)

np.int64(1400)

Max Norm

In [227]:
np.linalg.norm(x, ord=np.inf)

np.float64(30.0)

Orthogonal vectors

In [228]:
i = np.array([1, 0])
j = np.array([0, 1])

np.dot(i, j)

np.int64(0)

Matrices in NumPy

In [229]:
X = np.array([[25, 2], [5, 26], [3, 7]])
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [230]:
X.shape

(3, 2)

In [231]:
X.size

6

In [232]:
X[:, 0]

array([25,  5,  3])

In [233]:
X[2, :]

array([3, 7])

Matrices in PyTorch

In [234]:
X_pt = torch.tensor([[25, 2], [5, 26], [3, 7]])
X_pt

tensor([[25,  2],
        [ 5, 26],
        [ 3,  7]])

In [235]:
X_pt.shape #Pythonic

torch.Size([3, 2])

In [236]:
X_pt[2, :]

tensor([3, 7])

Matrices in TensorFlow

In [237]:
X_tf = tf.Variable([[25, 2], [5, 26], [3, 7]])
X_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[25,  2],
       [ 5, 26],
       [ 3,  7]], dtype=int32)>

In [238]:
tf.shape(X_tf)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 2], dtype=int32)>

In [239]:
tf.rank(X_tf) # rank 2 means Matrix

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [240]:
X_tf[1, :]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 5, 26], dtype=int32)>

Higher rank tensors
Rank 4 tensors are commonn for images, where each dimension corresponds to:
1. Number of images in training batch
2. Image height in pixels
3. Image width in pixels
4. Number of color channels

In [241]:
images_pt = torch.zeros([32, 28, 28,3])

In [242]:
images_pt

tensor([[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         ...,

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0.

In [243]:
images_tf = tf.zeros([32, 28, 28,3])

In [244]:
images_tf

<tf.Tensor: shape=(32, 28, 28, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        ...,

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


   

Tensor Transpose

In [245]:
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [246]:
X.T

array([[25,  5,  3],
       [ 2, 26,  7]])

In [247]:
X_pt

tensor([[25,  2],
        [ 5, 26],
        [ 3,  7]])

In [248]:
X_pt.T

tensor([[25,  5,  3],
        [ 2, 26,  7]])

In [249]:
X_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[25,  2],
       [ 5, 26],
       [ 3,  7]], dtype=int32)>

In [250]:
tf.transpose(X_tf) # Less pythonic

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[25,  5,  3],
       [ 2, 26,  7]], dtype=int32)>

Basic Arithmatic Properties

In [251]:
X * 2

array([[50,  4],
       [10, 52],
       [ 6, 14]])

In [252]:
X * 2 + 2

array([[52,  6],
       [12, 54],
       [ 8, 16]])

In [253]:
torch.add(X_pt, 2)

tensor([[27,  4],
        [ 7, 28],
        [ 5,  9]])

In [254]:
tf.add(X_tf, 5)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[30,  7],
       [10, 31],
       [ 8, 12]], dtype=int32)>

In [255]:
torch.mul(torch.add(X_pt, 2), 3)

tensor([[81, 12],
        [21, 84],
        [15, 27]])

In [256]:
tf.multiply(tf.add(X_tf, 3), 3)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[84, 15],
       [24, 87],
       [18, 30]], dtype=int32)>

Element wist operations (Not Matrix Multiplication)

In [257]:
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [258]:
A = X + 2
A

array([[27,  4],
       [ 7, 28],
       [ 5,  9]])

In [259]:
A * X

array([[675,   8],
       [ 35, 728],
       [ 15,  63]])

In [260]:
A + X

array([[52,  6],
       [12, 54],
       [ 8, 16]])

In [261]:
A_pt = X_pt +2

torch.mul(A_pt, X_pt)

tensor([[675,   8],
        [ 35, 728],
        [ 15,  63]])

In [262]:
torch.add(X_pt, A_pt)

tensor([[52,  6],
        [12, 54],
        [ 8, 16]])

In [263]:
A_tf = tf.add(X_tf, 2)
tf.add(A_tf, X_tf)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[52,  6],
       [12, 54],
       [ 8, 16]], dtype=int32)>

In [264]:
tf.multiply(X_tf, A_tf)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[675,   8],
       [ 35, 728],
       [ 15,  63]], dtype=int32)>

Reduction

In [265]:
X.sum()

np.int64(68)

In [266]:
torch.sum(X_pt)

tensor(68)

In [267]:
tf.reduce_sum(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=68>

In [268]:
tf.reduce_sum(X_tf, axis=1)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([27, 31, 10], dtype=int32)>

Dot Product

In [269]:
x

array([10, 20, 30])

In [270]:
y

array([[10, 20, 30]])

In [271]:
np.dot(x, y.T)

array([1400])

In [272]:
x_pt

tensor([1, 2, 3])

In [273]:
y_pt = torch.add(x_pt, 2)
y_pt

tensor([3, 4, 5])

In [274]:
torch.dot(x_pt, y_pt)

tensor(26)

In [275]:
x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [276]:
y_tf = tf.add(x_tf, 2)
y_tf

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 4, 5], dtype=int32)>

In [277]:
tf.reduce_sum(tf.multiply(x_tf, y_tf))

<tf.Tensor: shape=(), dtype=int32, numpy=26>

Matrix Multiplication

In [278]:
A = np.array([[3, 4], [5, 6], [7, 8]])
A

array([[3, 4],
       [5, 6],
       [7, 8]])

In [279]:
b = np.array([1,2])
b

array([1, 2])

In [280]:
np.dot(A, b)

array([11, 17, 23])

In [281]:
A_pt = torch.tensor([[3, 4], [5, 6], [7, 8]])
A_pt

tensor([[3, 4],
        [5, 6],
        [7, 8]])

In [282]:
b_pt = torch.tensor([1, 2])
b_pt

tensor([1, 2])

In [283]:
torch.matmul(A_pt, b_pt)

tensor([11, 17, 23])

In [284]:
A_tf = tf.Variable([[3, 4], [5, 6], [7, 8]])
A_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[3, 4],
       [5, 6],
       [7, 8]], dtype=int32)>

In [285]:
b_tf = tf.Variable([1, 2])
b_tf

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>

In [286]:
tf.linalg.matvec(A_tf, b_tf)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([11, 17, 23], dtype=int32)>

In [287]:
B = np.array([[1, 9], [2, 0]])
B

array([[1, 9],
       [2, 0]])

In [288]:
np.dot(A, B)

array([[11, 27],
       [17, 45],
       [23, 63]])

In [289]:
B_pt = torch.tensor([[1, 9], [2,0]])
B_pt

tensor([[1, 9],
        [2, 0]])

In [290]:
torch.matmul(A_pt, B_pt)

tensor([[11, 27],
        [17, 45],
        [23, 63]])

In [291]:
B_tf = tf.Variable([[1, 9], [2, 0]])
B_tf

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 9],
       [2, 0]], dtype=int32)>

In [292]:
tf.linalg.matmul(A_tf, B_tf)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[11, 27],
       [17, 45],
       [23, 63]], dtype=int32)>

Symmetric Matrices

In [293]:
X_sym = np.array([[1, 5, 4], [5, 7, 9], [4, 9, 5]])
X_sym

array([[1, 5, 4],
       [5, 7, 9],
       [4, 9, 5]])

In [294]:
X_sym.T

array([[1, 5, 4],
       [5, 7, 9],
       [4, 9, 5]])

In [295]:
X_sym.T == X_sym

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [296]:
X_pt_sym = torch.tensor([[1, 5, 4], [5, 7, 9], [4, 9, 5]])
X_pt_sym

tensor([[1, 5, 4],
        [5, 7, 9],
        [4, 9, 5]])

In [297]:
X_pt_sym.T

tensor([[1, 5, 4],
        [5, 7, 9],
        [4, 9, 5]])

In [298]:
X_pt_sym.T == X_pt_sym

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [299]:
X_tf_sym = tf.Variable([[1, 5, 4], [5, 7, 9], [4, 9, 5]])
X_tf_sym

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[1, 5, 4],
       [5, 7, 9],
       [4, 9, 5]], dtype=int32)>

In [300]:
tf.transpose(X_tf_sym)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 5, 4],
       [5, 7, 9],
       [4, 9, 5]], dtype=int32)>

In [301]:
tf.transpose(X_tf_sym) == X_tf_sym

<tf.Tensor: shape=(3, 3), dtype=bool, numpy=
array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])>

Identity Matrices

In [302]:
I = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
I

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [303]:
np.dot(x, I)

array([10, 20, 30])

In [304]:
I_pt = torch.tensor([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
I_pt

tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])

In [305]:
x_pt

tensor([1, 2, 3])

In [306]:
torch.matmul(x_pt, I_pt)

tensor([1, 2, 3])

In [307]:
I_tf = tf.Variable([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
I_tf

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int32)>

In [308]:
x_tf = tf.reshape(x_tf, (1,3)) #Reshaping is needed as TensorFlow does not allow Vector to Metrix multiplication directly without converting the vector to row vector.

In [309]:
tf.linalg.matvec(x_tf, I_tf)

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3]], dtype=int32)>