Scalars in PyTorch

In [2]:
import torch

In [3]:
x_pt = torch.tensor(10)
x_pt

tensor(10)

In [4]:
x_pt.shape #Scalar tensor has no dimention. Only magnitude.

torch.Size([])

Scalars in TensorFlow

In [5]:
import tensorflow as tf

c:\Users\jadej\AppData\Local\Programs\Python\Python313\Lib\site-packages\google\protobuf\runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/attr_value.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
c:\Users\jadej\AppData\Local\Programs\Python\Python313\Lib\site-packages\google\protobuf\runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/tensor.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
c:\Users\jadej\AppData\Local\Programs\Python\Python313\Lib\site-packages\google\protobuf\runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framewo

In [6]:
x_tf = tf.Variable(10, dtype=tf.int16)

In [7]:
x_tf

<tf.Variable 'Variable:0' shape=() dtype=int16, numpy=10>

In [8]:
x_tf.shape

TensorShape([])

In [9]:
y_tf = tf.Variable(15, dtype=tf.int16)

In [10]:
x_tf + y_tf #Overloading the operators. Using base Python operators on tensors.

<tf.Tensor: shape=(), dtype=int16, numpy=25>

In [11]:
tf_sum = tf.add(x_tf, y_tf)
tf_sum

<tf.Tensor: shape=(), dtype=int16, numpy=25>

In [12]:
tf_sum.numpy()

np.int16(25)

Vectors in NumPy  
#arrays cannot be created in base Python

In [13]:
import numpy as np

In [14]:
x = np.array([10, 20, 30])
x

array([10, 20, 30])

In [15]:
len(x)

3

In [16]:
x.shape

(3,)

In [17]:
type(x)

numpy.ndarray

In [18]:
x[0]

np.int64(10)

Vector Transposition

Transposing a regular 1-D array has not effect, unless we use a nested "matrix-style" bracket.

In [19]:
x

array([10, 20, 30])

In [20]:
x_t = x.T
x_t

array([10, 20, 30])

In [21]:
y = np.array([[10, 20, 30]])
y

array([[10, 20, 30]])

In [22]:
y.T

array([[10],
       [20],
       [30]])

Zero vectors

In [23]:
z = np.zeros(3)
z

array([0., 0., 0.])

Vectors in PyTorch and TensorFlow

In [24]:
x_pt = torch.tensor([1, 2, 3])
x_pt

tensor([1, 2, 3])

In [25]:
x_tf = tf.Variable([1, 2, 3])
x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

L<sup>2</sup> Norm

In [26]:
x

array([10, 20, 30])

In [27]:
np.linalg.norm(x)

np.float64(37.416573867739416)

L<sup>1</sup> Norm

In [28]:
np.linalg.norm(x, ord= 1)

np.float64(60.0)

Squared L<sup>2</sup> Norm

In [29]:
x

array([10, 20, 30])

In [30]:
np.dot(x, x)

np.int64(1400)

Max Norm

In [31]:
np.linalg.norm(x, ord=np.inf)

np.float64(30.0)

Orthogonal vectors

In [32]:
i = np.array([1, 0])
j = np.array([0, 1])

np.dot(i, j)

np.int64(0)

Matrices in NumPy

In [33]:
X = np.array([[25, 2], [5, 26], [3, 7]])
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [34]:
X.shape

(3, 2)

In [35]:
X.size

6

In [36]:
X[:, 0]

array([25,  5,  3])

In [37]:
X[2, :]

array([3, 7])

Matrices in PyTorch

In [38]:
X_pt = torch.tensor([[25, 2], [5, 26], [3, 7]])
X_pt

tensor([[25,  2],
        [ 5, 26],
        [ 3,  7]])

In [39]:
X_pt.shape #Pythonic

torch.Size([3, 2])

In [40]:
X_pt[2, :]

tensor([3, 7])

Matrices in TensorFlow

In [41]:
X_tf = tf.Variable([[25, 2], [5, 26], [3, 7]])
X_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[25,  2],
       [ 5, 26],
       [ 3,  7]], dtype=int32)>

In [42]:
tf.shape(X_tf)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 2], dtype=int32)>

In [43]:
tf.rank(X_tf) # rank 2 means Matrix

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [44]:
X_tf[1, :]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 5, 26], dtype=int32)>

Higher rank tensors
Rank 4 tensors are commonn for images, where each dimension corresponds to:
1. Number of images in training batch
2. Image height in pixels
3. Image width in pixels
4. Number of color channels

In [45]:
images_pt = torch.zeros([32, 28, 28,3])

In [46]:
images_pt

tensor([[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         ...,

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0.

In [47]:
images_tf = tf.zeros([32, 28, 28,3])

In [48]:
images_tf

<tf.Tensor: shape=(32, 28, 28, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        ...,

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


   

Tensor Transpose

In [49]:
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [50]:
X.T

array([[25,  5,  3],
       [ 2, 26,  7]])

In [51]:
X_pt

tensor([[25,  2],
        [ 5, 26],
        [ 3,  7]])

In [52]:
X_pt.T

tensor([[25,  5,  3],
        [ 2, 26,  7]])

In [53]:
X_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[25,  2],
       [ 5, 26],
       [ 3,  7]], dtype=int32)>

In [58]:
tf.transpose(X_tf) # Less pythonic

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[25,  5,  3],
       [ 2, 26,  7]], dtype=int32)>

Basic Arithmatic Properties

In [59]:
X * 2

array([[50,  4],
       [10, 52],
       [ 6, 14]])

In [60]:
X * 2 + 2

array([[52,  6],
       [12, 54],
       [ 8, 16]])

In [62]:
torch.add(X_pt, 2)

tensor([[27,  4],
        [ 7, 28],
        [ 5,  9]])

In [63]:
tf.add(X_tf, 5)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[30,  7],
       [10, 31],
       [ 8, 12]], dtype=int32)>

In [64]:
torch.mul(torch.add(X_pt, 2), 3)

tensor([[81, 12],
        [21, 84],
        [15, 27]])

In [65]:
tf.multiply(tf.add(X_tf, 3), 3)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[84, 15],
       [24, 87],
       [18, 30]], dtype=int32)>

Element wist operations (Not Matrix Multiplication)

In [72]:
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [73]:
A = X + 2
A

array([[27,  4],
       [ 7, 28],
       [ 5,  9]])

In [71]:
A * X

array([[675,   8],
       [ 35, 728],
       [ 15,  63]])

In [75]:
A + X

array([[52,  6],
       [12, 54],
       [ 8, 16]])

In [79]:
A_pt = X_pt +2

torch.mul(A_pt, X_pt)

tensor([[675,   8],
        [ 35, 728],
        [ 15,  63]])

In [81]:
torch.add(X_pt, A_pt)

tensor([[52,  6],
        [12, 54],
        [ 8, 16]])

In [83]:
A_tf = tf.add(X_tf, 2)
tf.add(A_tf, X_tf)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[52,  6],
       [12, 54],
       [ 8, 16]], dtype=int32)>

In [84]:
tf.multiply(X_tf, A_tf)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[675,   8],
       [ 35, 728],
       [ 15,  63]], dtype=int32)>

Reduction

In [86]:
X.sum()

np.int64(68)

In [89]:
torch.sum(X_pt)

tensor(68)

In [88]:
tf.reduce_sum(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=68>

In [91]:
tf.reduce_sum(X_tf, axis=1)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([27, 31, 10], dtype=int32)>

Dot Product

In [92]:
x

array([10, 20, 30])

In [93]:
y

array([[10, 20, 30]])

In [95]:
np.dot(x, y.T)

array([1400])

In [96]:
x_pt

tensor([1, 2, 3])

In [101]:
y_pt = torch.add(x_pt, 2)
y_pt

tensor([3, 4, 5])

In [102]:
torch.dot(x_pt, y_pt)

tensor(26)

In [103]:
x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [106]:
y_tf = tf.add(x_tf, 2)
y_tf

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 4, 5], dtype=int32)>

In [108]:
tf.reduce_sum(tf.multiply(x_tf, y_tf))

<tf.Tensor: shape=(), dtype=int32, numpy=26>

Matrix Multiplication

In [109]:
A = np.array([[3, 4], [5, 6], [7, 8]])
A

array([[3, 4],
       [5, 6],
       [7, 8]])

In [111]:
b = np.array([1,2])
b

array([1, 2])

In [112]:
np.dot(A, b)

array([11, 17, 23])

In [125]:
A_pt = torch.tensor([[3, 4], [5, 6], [7, 8]])
A_pt

tensor([[3, 4],
        [5, 6],
        [7, 8]])

In [126]:
b_pt = torch.tensor([1, 2])
b_pt

tensor([1, 2])

In [128]:
torch.matmul(A_pt, b_pt)

tensor([11, 17, 23])

In [129]:
A_tf = tf.Variable([[3, 4], [5, 6], [7, 8]])
A_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[3, 4],
       [5, 6],
       [7, 8]], dtype=int32)>

In [131]:
b_tf = tf.Variable([1, 2])
b_tf

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>

In [135]:
tf.linalg.matvec(A_tf, b_tf)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([11, 17, 23], dtype=int32)>

In [139]:
B = np.array([[1, 9], [2, 0]])
B

array([[1, 9],
       [2, 0]])

In [141]:
np.dot(A, B)

array([[11, 27],
       [17, 45],
       [23, 63]])

In [142]:
B_pt = torch.tensor([[1, 9], [2,0]])
B_pt

tensor([[1, 9],
        [2, 0]])

In [143]:
torch.matmul(A_pt, B_pt)

tensor([[11, 27],
        [17, 45],
        [23, 63]])

In [145]:
B_tf = tf.Variable([[1, 9], [2, 0]])
B_tf

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 9],
       [2, 0]], dtype=int32)>

In [146]:
tf.linalg.matmul(A_tf, B_tf)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[11, 27],
       [17, 45],
       [23, 63]], dtype=int32)>

Symmetric Matrices

In [149]:
X_sym = np.array([[1, 5, 4], [5, 7, 9], [4, 9, 5]])
X_sym

array([[1, 5, 4],
       [5, 7, 9],
       [4, 9, 5]])

In [150]:
X_sym.T

array([[1, 5, 4],
       [5, 7, 9],
       [4, 9, 5]])

In [151]:
X_sym.T == X_sym

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
X_pt_sym = torch.tensor([[1, 5, 4], [5, 7, 9], [4, 9, 5]])
X_pt_sym

tensor([[1, 5, 4],
        [5, 7, 9],
        [4, 9, 5]])

In [162]:
X_pt_sym.T

tensor([[1, 5, 4],
        [5, 7, 9],
        [4, 9, 5]])

In [163]:
X_pt_sym.T == X_pt_sym

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [165]:
X_tf_sym = tf.Variable([[1, 5, 4], [5, 7, 9], [4, 9, 5]])
X_tf_sym

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[1, 5, 4],
       [5, 7, 9],
       [4, 9, 5]], dtype=int32)>

In [166]:
tf.transpose(X_tf_sym)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 5, 4],
       [5, 7, 9],
       [4, 9, 5]], dtype=int32)>

In [167]:
tf.transpose(X_tf_sym) == X_tf_sym

<tf.Tensor: shape=(3, 3), dtype=bool, numpy=
array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])>

Identity Matrices

In [170]:
I = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
I

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [171]:
np.dot(x, I)

array([10, 20, 30])

In [172]:
I_pt = torch.tensor([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
I_pt

tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])

In [173]:
x_pt

tensor([1, 2, 3])

In [175]:
torch.matmul(x_pt, I_pt)

tensor([1, 2, 3])

In [176]:
I_tf = tf.Variable([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
I_tf

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int32)>

In [196]:
x_tf = tf.reshape(x_tf, (1,3)) #Reshaping is needed as TensorFlow does not allow Vector to Metrix multiplication directly without converting the vector to row vector.

In [197]:
tf.linalg.matvec(x_tf, I_tf)

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3]], dtype=int32)>